- name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          if (Test-Path requirements.txt) { pip install -r requirements.txt }
          pip install pyusb libusb customtkinter darkdetect 
          pip install Pillow  # <--- This fixes the ModuleNotFoundError: No module named 'PIL'

      - name: Build with PyInstaller
        run: |
          # We add --add-data to include your folders so the EXE isn't "empty"
          # Format: "source_folder;destination_folder"
          pyinstaller --noconsole --onefile `
            --add-data "resources;resources" `
            --add-data "lang;lang" `
            --add-data "devices;devices" `
            gui.py
